gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

pvrezcomment_add:
    path:  /comment/add/{contentId}
    defaults: { _controller: PvrEzCommentBundle:Comment:addComment }
    requirements:
        _method: POST
        contentId: \d+

pvrezcomment_moderation:
    path: /comment/{action}/{contentId}/{sessionHash}/{commentId}
    defaults: { _controller: PvrEzCommentBundle:Comment:commentModerate }
    requirements:
        contentId: \d+
        action: approve|reject
        commentId: \d+

pvrezcomment_dashboard:
    path: /dashboard
    defaults:
        _controller: pvr_ezcomment.controller.dashboard:dashboardAction