parameters:
    pvr_ezcomment.encryption.class: pvr\EzCommentBundle\Comment\PvrEzCommentEncryption
    pvr_ezcomment.manager.class: pvr\EzCommentBundle\Comment\PvrEzCommentManager
    pvr_ezcomment.maxage: 60
    pvr_ezcomment.twig_extension.class: pvr\EzCommentBundle\Twig\PvrEzCommentExtension
    pvr_ezcomment.service.class: pvr\EzCommentBundle\Service\Comment

    ezpublish.api.role.limitation_type.content_section.class: eZ\Publish\Core\Limitation\SectionLimitationType


services:
    pvr_ezcomment.manager:
        class: "%pvr_ezcomment.manager.class%"
        arguments:
            - "%pvr_ezcomment.config%"
            - "@mailer"
            - "@pvr_ezcomment.encryption"
            - "@router"
        calls:
            - [ setTranslator, ["@translator"] ]
            - [ setFormFactory, ["@form.factory"] ]
            - [ setTwig, ["@twig"] ]

    pvr_ezcomment.encryption:
        class: "%pvr_ezcomment.encryption.class%"
        arguments:
            - "%secret%"

    ezpublish.api.role.limitation_type.content_section:
        class: "%ezpublish.api.role.limitation_type.content_section.class%"
        arguments: ["@ezpublish.api.persistence_handler"]
        tags:
            - {name: ezpublish.limitationType, alias: ContentSection}

    ezpublish.twig.pvrezcomment_extension:
        class: "%pvr_ezcomment.twig_extension.class%"
        arguments: ["@pvr_ezcomment.manager", "@ezpublish.connection"]
        lazy: true
        tags:
            - { name: twig.extension }

    pvr_ezcomment.service:
        class: "%pvr_ezcomment.service.class%"
        calls:
            - [setRequest, ["@request_stack"]]
            - [setSecurity, ["@security.context"]]
        arguments:
            - "@pvr_ezcomment.manager"
            - "@ezpublish.connection"
            - "@ezpublish.locale.converter"
            - "@translator"
            - "@ezpublish.api.repository"


