parameters:
    pvr_ezcomment.maxage: 60

services:
    # Installer for pvrezcomments
    pvr_ezcomment.installer.comment_installer:
        parent: ezplatform.installer.db_based_installer
        class: pvr\EzCommentBundle\Installer\CommentInstaller
        tags:
            - { name: ezplatform.installer, type: comment }

    pvr_ezcomment.manager:
        class: pvr\EzCommentBundle\Comment\PvrEzCommentManager
        arguments:
            - "%pvr_ezcomment.config%"
            - "@mailer"
            - "@pvr_ezcomment.encryption"
            - "@router"
            - "@ezpublish.persistence.connection"
        calls:
            - [ setFormFactory, ["@form.factory"] ]
            - [ setTwig, ["@twig"] ]

    pvr_ezcomment.encryption:
        class: pvr\EzCommentBundle\Comment\PvrEzCommentEncryption
        arguments:
            - "%secret%"

    ezpublish.api.role.limitation_type.content_section:
        class: eZ\Publish\Core\Limitation\SectionLimitationType
        arguments: ["@ezpublish.api.persistence_handler"]
        tags:
            - {name: ezpublish.limitationType, alias: ContentSection}

    ezpublish.twig.pvrezcomment_extension:
        class: pvr\EzCommentBundle\Twig\PvrEzCommentExtension
        arguments:
            - "@pvr_ezcomment.manager"
            - "@ezpublish.connection"
            - "@ezpublish.api.service.content"
            - "@ezpublish.translation_helper"
            - "@ezpublish.api.service.location"
        tags:
            - { name: twig.extension }

    pvr_ezcomment.service:
        class: pvr\EzCommentBundle\Service\Comment
        calls:
            - [setSecurity, ["@security.authorization_checker"]]
        arguments:
            - "@pvr_ezcomment.manager"
            - "@ezpublish.connection"
            - "@ezpublish.locale.converter"
            - "@translator"
            - "@ezpublish.api.repository"

    # Pjax Dashboard Controller service
    pvr_ezcomment.controller.dashboard:
        class: pvr\EzCommentBundle\Controller\DashboardController

    # Rest Controller
    pvrEzCommentBundle.controller.comment:
        class: pvr\EzCommentBundle\Rest\Controller\CommentController
        parent: ezpublish_rest.controller.base

    pvr\EzCommentBundle\Controller\CommentController:
        arguments:
            $commentService: "@pvr_ezcomment.service"
            $commentManager: "@pvr_ezcomment.manager"
            $translator: "@translator"
            $maxAge: '%pvr_ezcomment.maxage%'
